var pastProjects = [
    {   name: "Energy Made in Uganda",
        category: "Renewable Energy",
        numOfStudents: 2,
        student0: "Jaqueline Barbosa",
        student1: "Kirsten Petersen",
        advisor: "Shoba Krisnan, Associate Professor of Electrical Engineering",
        description: "blahblahblah"
    },
    {   name: "Dynamic Poverty Heat Map",
        category: "Renewable Energy",
        numOfStudents: 3,
        student0: "Johnathan Ahumada",
        student1: "Kurt Jurgens",
        student2: "Jasmine Farias",
        advisor: "Silvia Figueira, Associate Professor of Computer Engineering",
        description: "blahblahblah"
    },
    {   name: "QuikChill",
        category: "Renewable Energy",
        numOfStudents: 3,
        student0: "Franz Louie Chua",
        student1: "Brandon Ohara",
        student2: "Bernadette Tong",
        advisor: "Hohyun Lee, Assistant Professor of Mechanical Engineering",
        description: "blahblahblah"
    },
    {   name: "Emergency Power for Hospitals in Under-Developed Countries",
        category: "Renewable Energy",
        numOfStudents: 3,
        student0: "Erik McAdams",
        student1: "Hugo Mailloux-Beauchemin",
        student2: "Jonathan Chimento",
        advisor: "Tonya Nilsson, Full-Time Lecturer of Civil Engineering",
        description: "blahblahblah"
    },
    {   name: "MUVE",
        category: "Renewable Energy",
        numOfStudents: 4,
        student0: "Elysia Chu",
        student1: "Victoria Hall",
        student2: "Maya Hough",
        student3: "Urvashi Reddy",
        advisor: "Silvia Figueira, Associate Professor of Computer Engineering\nRadha R. Basu, Regis and Dianne McKenna Executive Professor of Engineering",
        description: "'MUVE’-ing better jobs and education to change lives.\n A web tool to digitize books for use in rural areas. Computer engineering students designed this tool to be implemented for a social enterprise called 'iMerit' that generates new economy livelihoods in India (CEO of iMerit is Radha Basu, Director of the Frugal Innovation Lab). Considers the fact that feature phones are common, schools have outdated books, and women want and need jobs. iMerit works with employees and publishers, who then utilize MUVE to digitize relevant content. With the aim of providing a better education and enabling more jobs to be generated, MUVE is currently being deployed by a team of SCU students in rural centers in India."
    },
    {   name: "Fuel Cell Project",
        category: "Renewable Energy",
        numOfStudents: 2,
        student0: "Michael Sizemore",
        student1: "Sandeep Lele",
        advisor: "Drazen Fabris",
        description: ""
    },
    {   name: "Lab on a Chip",
        category: "Clean Water",
        numOfStudents: 5,
        student0: "Sonny Gandhi",
        student1: "Zuhayr Elahi",
        student2: "John Seubert",
        student3: "Ben Demaree",
        student4: "Jessica VanderGiessen",
        advisor: "Shoba Krishnan, Associate Professor of Electrical Engineering\nSilvia Figueira, Associate Professor of Computer Engineering\nUnyoung (Ashley) Kim, Assistant Professor of Bioengineering",
        description: ""
    },